[package]
name = "ipfn"
version = "0.1.0"
authors = ["Lukasz Kurowski <crackcomm@gmail.com>"]

[lib]
name = "ipfn"
path = "lib.rs"

[dependencies]
ipfn_core = { path = "./core" }
ipfn_proto = { path = "./proto" }
