[package]
name = "ipfn_core"
version = "0.1.0"
authors = ["Lukasz Kurowski <crackcomm@gmail.com>"]

[lib]
name = "ipfn_core"
path = "lib.rs"

[dependencies]
ipfn_proto = { path = "../proto" }

capnp = "0.8"

